context:
  version: "0.19.5"

package:
  name: create-rslib
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-rslib/-/create-rslib-${{ version }}.tgz
  sha256: 4d1e3bc03757064231ee703a88edb38f8214f1ef8a239053db3fea31b46d5d9d

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - create-rslib --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Create a new Rslib project
  homepage: https://lib.rsbuild.dev/
  repository: https://github.com/web-infra-dev/rslib

extra:
  recipe-maintainers:
    - danielnachun
