context:
  version: "0.13.1"

package:
  name: create-rslib
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-rslib/-/create-rslib-${{ version }}.tgz
  sha256: d76b895d326a89498a9f1f0cd1fffc9c96590abfe20e19233f01986f1dec3999

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - create-rslib --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Create a new Rslib project
  homepage: https://lib.rsbuild.dev/
  repository: https://github.com/web-infra-dev/rslib

extra:
  recipe-maintainers:
    - danielnachun
