context:
  version: "0.21.4"

package:
  name: create-rslib
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-rslib/-/create-rslib-${{ version }}.tgz
  sha256: 201d85d8aaf288223ef7156806230970ecf23b8c5b9a0faf6abafc0f62aac7d5

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - create-rslib --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Create a new Rslib project
  homepage: https://lib.rsbuild.dev/
  repository: https://github.com/web-infra-dev/rslib

extra:
  recipe-maintainers:
    - danielnachun
