context:
  version: "0.6.7"

package:
  name: create-rslib
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-rslib/-/create-rslib-${{ version }}.tgz
  sha256: b71d7bd4740c441aa4e32afa2347f7349954e0697be9c910b193c1c1bbdbd0ce

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - create-rslib --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Create a new Rslib project
  homepage: https://lib.rsbuild.dev/
  repository: https://github.com/web-infra-dev/rslib

extra:
  recipe-maintainers:
    - danielnachun
