context:
  version: "0.21.2"

package:
  name: create-rslib
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-rslib/-/create-rslib-${{ version }}.tgz
  sha256: 6f3163cb2b31fb36091f068260b5f4671654a92ced930571bed2637b0b97e533

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - create-rslib --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Create a new Rslib project
  homepage: https://lib.rsbuild.dev/
  repository: https://github.com/web-infra-dev/rslib

extra:
  recipe-maintainers:
    - danielnachun
